### ISSUE TITLE
How do the TTF/OTF formats differ?

### ISSUE THREAD

**Issue by behdad** [rudymohammadbali/FontConverter#1]
I don't see any conversion between TrueType-flavors vs Postscript-flavored fonts. So what's with those two formats?

For what it's worth, you can do the same work using `fonttools ttLib --flavor` command.

**Comment by rudymohammadbali** [comment]
What are you talking about?

**Comment by davelab6** [comment]
https://www.google.com/search?q=opentype+flavors

**Comment by rudymohammadbali** [comment]
Fixing now!

**Comment by behdad** [comment]
> Fixing now!

Can you please tell us what you fixed exactly?

**Comment by rudymohammadbali** [comment]
@behdad bro chill, i don't have time.

**Comment by rudymohammadbali** [comment]
Make pull if you are so hurry!

**Comment by davelab6** [comment]
I think the problem we are concerned about is that your tool does not actually do what it's name and basic docs say it does - but the fonttools library supplies all the needed functionality to really do it.
